### PR TITLE
New header

### PR DESCRIPTION
**Pull request by sabawaheed27**

### CODE REVIEW

**Comment by sabawaheed27** [comment]
I fixed the images

**Comment by bushra-rauf** [comment]
yes images are fixed but still i you need to fix your nav bar and page -title need to be in the center.

**Comment by Moshira89** [comment]
your header and footer is missing . yeah I can see your images.

**Comment by bushra-rauf** [comment]
yes images are fixed but still i you need to fix your nav bar and page -title need to be in the center.

**Pull request closed without merging**
