### PR TITLE
added page-title on project,branhing-page and on  branching-p worked …

### PR DESCRIPTION
**Pull request by bushra-rauf**
I have added page-title on project-page and branching. On branching page unwanted text deleted and. background colour changed to make a look as other pages. and text bar colour and font colour changed.

### CODE REVIEW

**Comment by sabawaheed27** [comment]
nice work

**Comment by sabawaheed27** [comment]
it seems everything is done now.

**Comment by Moshira89** [comment]
Good work

**Review by mvic89 — APPROVED** [review]
Looking good.

**Pull request merged**
